language: python
sudo: false
python:
#  - "2.7"
  - "3.5"
  - "3.6"
cache: pip
services:
  - postgresql
addons:
  postgresql: "9.5"
  apt:
    packages:
      postgresql-9.5-postgis-2.3
env:
 - DEBUG=True
before_install:
  - rvm install 2.2
  - nvm install node
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt -r requirements-test.txt
  - gem install sass
  - npm install
before_script:
  - psql -U postgres -c 'create extension postgis'
  - psql -U postgres -c 'create database bustimes'
  - ./manage.py migrate
script:
  - ./manage.py collectstatic --noinput
  # - PYTHONWARNINGS=all coverage run manage.py test
  - coverage run manage.py test
  - flake8
  - echo $PATH
  - ./node_modules/.bin/sass-lint 'busstops/static/css/*' -v
  - ./node_modules/.bin/eslint 'busstops/static/js/*.js'
after_success:
  - coveralls
  - git status
