[tool.poetry]
name = "bustimes.org"
version = "0.1.0"
description = ""
authors = ["Josh Goodwin <j@joshuagoodw.in>"]

[tool.poetry.dependencies]
python = "<3.13,>=3.11"
asgiref = "^3.4.1"
beautifulsoup4 = "^4.12.1"
boto3 = "^1.18.42"
ciso8601 = "^2.2.0"
dj-database-url = "^2.0.0"
Django = "^5.0.1"
django-autoslug = "^1.9.8"
django-coverage-plugin = "^3.0.0"
django-email-obfuscator = "^0.1.5"
django-filter = "^24.1"
django-multidb-router = "^0.10"
djangorestframework = "^3.14.0"
django-simple-history = "^3.0.0"
django-slowtests = "^1.1.1"
django-sql-utils = "^0.7.0"
django-template-minifier = "^1.1.0"
gtfs-realtime-bindings = "^1.0.0"
gunicorn = "^21.1.0"
haversine = "^2.5.1"
huey = "^2.4.3"
numpy = "^1.26"
polyline = "^2.0.0"
protobuf = "^5.26.0"
psycopg = "^3.1.8"
PyYAML = "^6.0.0"
redis = "^5.0.0"
requests-cache = "^1.1.0"
sentry-sdk = {extras = ["django"], version = "^2.0.1"}
Shapely = "^2.0.1"
time-machine = "^2.4.0"
titlecase = "^2.3"
uk-postcode-utils = "^1.1"
vcrpy = "^6.0.0"
webcolors = "^1.11.1"
whitenoise = "^6.2.0"
xmltodict = "^0.13.0"
django-csp = "^3.7"
django-cors-headers = "^4.2.0"
pygments = "^2.15.1"
fakeredis = "^2.12.1"
django-turnstile = "^0.1.0"
tenacity = "^8.2.2"
requests-toolbelt = "^1.0.0"
gtfs-kit = "^6.0.0"
websockets = "^12.0"
lxml = "^5.0.0"
qrcode = "^7.4.2"
django-email-blacklist = "^1.0.1"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "^4.0.0"
django-debug-toolbar-force = "^0.2"
ipdb = "^0.13.9"
ipython = "^8.5.0"
pre-commit = "^3.3.3"
uritemplate = "^4.1.1"

[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
