[tool.poetry]
name = "bustimes.org"
version = "0.1.0"
description = ""
authors = ["Josh Goodwin <j@joshuagoodw.in>"]

[tool.poetry.dependencies]
python = "^3.10"
asgiref = "^3.4.1"
beautifulsoup4 = "^4.10.0"
boto3 = "^1.18.42"
channels-redis = "^4.0.0"
ciso8601 = "^2.2.0"
dj-database-url = "^1.0.0"
Django = "^4.1.6"
django-autoslug = "^1.9.8"
django-coverage-plugin = "^2.0.0"
django-email-obfuscator = "^0.1.5"
django-filter = "^22.1"
django-multidb-router = "^0.10"
django-rest-framework = "^0.1.0"
django-simple-history = "^3.0.0"
django-slowtests = "^1.1.1"
django-sql-utils = "^0.6.1"
django-template-minifier = "^1.1.0"
gtfs-realtime-bindings = "^0.0.7"
gunicorn = "^20.1.0"
haversine = "^2.5.1"
huey = "^2.4.3"
numpy = "^1.21.2"
polyline = "^1.4.0"
protobuf = "^3.20.3"
psycopg2 = "^2.9.1"
python-akismet = "^0.4.3"
PyYAML = "^6.0.0"
redis = "^4.0.2"
requests-cache = "^0.9.6"
requests-html = "^0.10.0"
requests-toolbelt = "^0.10.0"
sentry-sdk = "^1.3.1"
Shapely = "^1.8.0"
time-machine = "^2.4.0"
titlecase = "^2.3"
uk-postcode-utils = "^1.1"
vcrpy = "^4.1.1"
webcolors = "^1.11.1"
whitenoise = "^6.2.0"
xmltodict = "^0.13.0"
honeycomb-beeline = "^3.5.0"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "^3.2.2"
django-debug-toolbar-force = "^0.1.8"
django-rich = "^1.4.0"
ipdb = "^0.13.9"
ipython = "^8.5.0"
pre-commit = "^2.19.0"
uritemplate = "^4.1.1"

[tool.black]
target-version = ['py310']

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
