[tool.poetry]
name = "bustimes.org"
version = "0.1.0"
description = ""
authors = ["Josh Goodwin <j@joshuagoodw.in>"]

[tool.poetry.dependencies]
python = "^3.9"
ciso8601 = "^2.2.0"
django-sql-utils = "^0.6.1"
Django = "^3.2.7"
channels-redis = "^3.3.0"
honeycomb-beeline = "^2.17.1"
chardet = "^4.0.0"
webcolors = "^1.11.1"
sentry-sdk = "^1.3.1"
xmltodict = "^0.12.0"
vcrpy = "^4.1.1"
time-machine = "^2.4.0"
celery = "^5.1.2"
django-antispam = "^1.0.3"
django-autoslug = "^1.9.8"
django-template-minifier = "^1.1.0"
django-email-obfuscator = "^0.1.5"
django-rest-framework = "^0.1.0"
django-filter = "^2.4.0"
boto3 = "^1.18.42"
psycopg2 = "^2.9.1"
django-slowtests = "^1.1.1"
django-redis = "^5.0.0"
haversine = "^2.5.1"
uk-postcode-utils = "^1.1"
gtfs-realtime-bindings = "^0.0.7"
beautifulsoup4 = "^4.10.0"
requests-html = "^0.10.0"
titlecase = "^2.3"
PyYAML = "^5.4.1"
django-coverage-plugin = "^2.0.0"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "^3.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
